export const LOGIN = "LOGIN";
export const SET_USER = "SET_USER";
export const LOGOUT = "LOGOUT";

export const GET_NOTIFICATION = "GET_NOTIFICATION";

export const GET_UPCOMING_EVENTS = "GET_UPCOMING_EVENTS";
export const GET_HOSTING_EVENT = "GET_HOSTING_EVENT";
export const GET_PENDING_EVENT = "GET_PENDING_EVENT";
export const GET_HISTORY_EVENT = "GET_HISTORY_EVENT";
export const GET_ATTENDING_EVENT = "GET_ATTENDING_EVENT";
export const GET_CANCEL_EVENT = "GET_CANCEL_EVENT";
export const GET_DETAIL_EVENT = "GET_DETAIL_EVENT";
export const PLACEPLAYWERONSEAT_EVENT = "PLACEPLAYWERONSEAT_EVENT";
export const CREATE_EVENT = "CREATE_EVENT";
export const EDIT_EVENT = "EDIT_EVENT";
export const JOIN_EVENT = "JOIN_EVENT";
export const PLACEVOTE_EVENT = "PLACEVOTE_EVENT";
export const ACCEPTPLAYER_EVENT = "ACCEPTPLAYER_EVENT";
export const REMOVEPLAYER_EVENT = "REMOVEPLAYER_EVENT";